commitment = "21098752700218543224960621296538648866114933415667035727129760525701482699380"
nullifier  = "3069450475750459734849294912166057482690135678412259269324911954590036259105"
shares     = "100000000000000000"
root       = "8326079081415951673246159411217231546671552569123413013130563508804834544546"
leaf_index = "0"

siblings = [
  "0","0","0","0","0","0","0","0",
  "0","0","0","0","0","0","0","0",
  "0","0","0","0","0","0","0","0",
  "0","0","0","0","0","0","0","0"
]

[witness]
secret       = "0x1234567890abcdef"
shares       = "100000000000000000"
deposit_time = 1700000001
blinding     = "0x9876543210fedcba"

