[package]
name = "commitment_calculator"
type = "bin"
authors = [""]
compiler_version = ">=0.35.0"

[dependencies]
poseidon = { git = "https://github.com/noir-lang/poseidon", tag = "v0.1.0" }
